[buildPlans.Iosolas]
family = "Iosolas"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

  [buildPlans.Iosolas.variants]
  inherits = "ss03"

    [buildPlans.Iosolas.variants.design]
    at = "threefold"

[buildPlans.Iosolas.widths.normal]
shape = 548
menu = 5
css = "normal"
